function y = filter_50(x,fs)
%FILTER_50 Filters input x and returns output y.

% MATLAB Code
% Generated by MATLAB(R) 8.5 and the DSP System Toolbox 9.0.
% Generated on: 02-May-2017 14:02:19

persistent Hd;

if isempty(Hd)
    
    N  = 4;      % Order
    F0 = 60;     % Center frequency
    Q  = 1;    % Q-factor
    Fs = fs;  % Sampling Frequency
    
    h = fdesign.notch('N,F0,Q', N, F0, Q, Fs);
    
    Hd = design(h, 'butter', ...
        'SOSScaleNorm', 'Linf');
    
    
    
    set(Hd,'PersistentMemory',true);
    
end

y = filter(Hd,x);


