function y = filter_dc(x)
%DOFILTER Filters input x and returns output y.

% MATLAB Code
% Generated by MATLAB(R) 9.4 and Signal Processing Toolbox 8.0.
% Generated on: 24-Apr-2019 10:19:20

persistent Hd;

if isempty(Hd)
    
    Fstop = 0.001;  % Stopband Frequency
    Fpass = 0.01;    % Passband Frequency
    Astop = 60;     % Stopband Attenuation (dB)
    Apass = 1;      % Passband Ripple (dB)
    Fs    = 256;    % Sampling Frequency
    
    h = fdesign.highpass('fst,fp,ast,ap', Fstop, Fpass, Astop, Apass, Fs);
    
    Hd = design(h, 'butter', ...
        'MatchExactly', 'stopband');
    
    
    
    set(Hd,'PersistentMemory',false);
    
end

y = filter(Hd,x);

