function y = filter_60Hz(x)
%DOFILTER Filters input x and returns output y.

% MATLAB Code
% Generated by MATLAB(R) 9.4 and Signal Processing Toolbox 8.0.
% Generated on: 24-Apr-2019 10:22:41

persistent Hd;

if isempty(Hd)
    
    Fpass1 = 56;   % First Passband Frequency
    Fstop1 = 57;   % First Stopband Frequency
    Fstop2 = 63;   % Second Stopband Frequency
    Fpass2 = 64;   % Second Passband Frequency
    Apass1 = 1;    % First Passband Ripple (dB)
    Astop  = 60;   % Stopband Attenuation (dB)
    Apass2 = 1;    % Second Passband Ripple (dB)
    Fs     = 256;  % Sampling Frequency
    
    h = fdesign.bandstop('fp1,fst1,fst2,fp2,ap1,ast,ap2', Fpass1, Fstop1, ...
        Fstop2, Fpass2, Apass1, Astop, Apass2, Fs);
    
    Hd = design(h, 'butter', ...
        'MatchExactly', 'stopband');
    
    
    
    set(Hd,'PersistentMemory',false);
    
end

y = filter(Hd,x);

